version: '3'

services:
  
  #query:
  #  depends_on:
  #    - querymongo
  #  image: queryservice
  #  build:
  #    context: .
  #    dockerfile: Dockerfile
  #  ports:
  #    - "4004:4004"
  #  environment:
  #    - HOST=querymongo:27004

  querymongo:
    command: mongod --port 27004
    build:
      context: ./db
      dockerfile: Dockerfile
    image: mongoquery
    ports:
      - "27004:27004"
    volumes: 
      - "/data/mongo:/data/db"